blank_issues_enabled: false
contact_links:
  - name: Don't ask me to add version.
    about: There's only so much I can do. If you have one to add, make a pull.
    url: https://github.com/Kingminer7/gdps-versions/issues/new/choose
